version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: three_tier_app

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      PORT: 5000
      MONGO_URI: mongodb://root:example@mongo:27017/three_tier_app?authSource=admin
      REDIS_URL: redis://redis:6379
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:

